version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - api-net

  api-web:
    image: jossuedaniel/api1-jdeg:api3.0
    command: ["./wait-for-it.sh", "db:5432", "--", "uwsgi", "--ini", "/src/config/uwsgi/uwsgi.ini"]
    restart: unless-stopped
    volumes:
      - .:/src
    ports:
      - target: 8000
        published: 5001
        protocol: tcp
        mode: host
    environment:
      - DJANGO_SETTINGS_MODULE=django_project.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - api-net

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/src
    ports:
      - "8023:8023"
    networks:
      - api-net

networks:
  api-net:
    external: true