# Generated by Django 5.0.6 on 2024-07-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=25)),
                ('descripcion', models.TextField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
    ]
