databases:
  - name: apidb
    plan: free
    databaseName: apidb
    user: apiBook

services:
  - type: web
    plan: free
    name: apiBook
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn django_project.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: apidb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4